# Generated by Django 5.0.6 on 2024-07-03 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_borrowitem'),
        ('book', '0002_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
    ]
